image: jdrouet/docker-with-buildx:stable

services:
  - docker:dind

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker buildx create --use
    # - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --pull --rm -f "Dockerfile" -t $CI_REGISTRY_IMAGE:latest "."
    - docker buildx build --platform linux/arm64/v8 --pull --rm -f "Dockerfile" -t $CI_REGISTRY_IMAGE:latest "."
    - docker images
    - docker push $CI_REGISTRY_IMAGE:latest